title: SNG Arsenal
logo: /assets/img/mod_icon.png
description: Star_SNG's first Minecraft mod, which adds SNG Arsenal into Minecraft.
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
