modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="GPL v3.0"
issueTrackerURL="https://github.com/StarSNG25/SNG-Arsenal" #optional
[[mods]] #mandatory
modId="sng_arsenal" #mandatory
version="${file.jarVersion}" #mandatory
displayName="SNG Arsenal" #mandatory
updateJSONURL="https://raw.githubusercontent.com/StarSNG25/SNG-Arsenal/1.19.4-forge/update.json" #optional
displayURL="https://sngarsenal.starsng.com/" #optional
logoFile="mod_icon.png" #optional
#credits="Made by Star_SNG" #optional
authors="Star_SNG" #optional
description='''
Star_SNG's first Minecraft mod, which adds SNG Arsenal into Minecraft.
'''
